db:
  host: "![CpWoRsKWa8FvclH7J2sb1b/1or9yyU9PZoXZNQ8fuB8dNFVNIOQdbg8v6IkrV4ujY0LmphiBpBLj+L0PkGqgdQ==]"
  port: "![xL/mOpAg35U=]"
  username: "![T1e3tFJtN5Y=]"
  password: "![87v5F99wtNeQ/kNr1zp6pw==]"
  database: "![Uds8ZnS4nE/LvlS8hCtYvA==]"